baseURL: "https://romanyanke.github.io/pencilbox"
# baseURL: "http://localhost:8080/"

theme: "pencil"
Paginate: 20


defaultContentLanguage: ru
languages:
  en:
    languageName: English
    weight: 2
  ru:
    languageName: Русский
    weight: 1

taxonomies:
  category: "categories"
  geo: "geo"
  city: "cities"
  tag: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true
