baseURL: "https://romanyanke.github.io/pencilbox"
# baseURL: "http://localhost:8080/"

theme: "pencil"
pagination:
  pagerSize: 20

caches:
  images:
    dir: :cacheDir/images

defaultContentLanguage: ru
languages:
  en:
    languageName: English
    weight: 2
  ru:
    languageName: Русский
    weight: 1

taxonomies:
  category: "categories"
  geo: "geo"
  city: "cities"
  tag: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true
